services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=studyplanner
      - DB_USER=root
      - DB_PASSWORD=saeidt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      database:
        condition: service_healthy
    stdin_open: true
    tty: true

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: saeidt
      MYSQL_DATABASE: studyplanner
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: