version: '3.8'

services:
  app:
    build: .
    image: saeid1993/sep01-project
    environment:
      - DISPLAY=host.docker.internal:0.0
    # The command now points to the special 'host.docker.internal' DNS name
    command: [ "java", "-Ddb.host=host.docker.internal", "--module-path", "libs", "--add-modules", "javafx.controls,javafx.fxml", "-cp", "app.jar:libs/*", "application.Main" ]

  database:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: saeidt
      MARIADB_DATABASE: studyplanner
    # Expose the database port to the host machine
    ports:
      - "3306:3306"
