services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_HOST=localhost  # Use localhost in host mode
      - DB_PORT=3306
      - DB_NAME=studyplanner
      - DB_USER=root
      - DB_PASSWORD=saeidt
    network_mode: host  # This makes the container use host network
    stdin_open: true
    tty: true