version: '3.8'
services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=studyplanner
      - DB_USER=root
      - DB_PASSWORD=saeidt
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - database
    stdin_open: true
    tty: true

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: saeidt
      MYSQL_DATABASE: studyplanner
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: