services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=studyplanner
      - DB_USER=root
      - DB_PASSWORD=saeidt
    network_mode: host
    stdin_open: true
    tty: true